import { fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Technical test',
  description: 'Generated by Camilo Vargas',
  authors: [
    {
      name: 'Camilo Vargas',
      url: 'https://www.linkedin.com/in/cavargasl/'
    }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen",
        fontSans.variable,
        fontMono.variable
      )}>{children}</body>
    </html>
  )
}
